name: SUL-GAME-FRONTEND

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set environment variables
      run: |
        echo "ANDROID_COMPILE_SDK=34" >> $GITHUB_ENV
        echo "ANDROID_TARGET_SDK=34" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew bundleRelease

    - name: Verify AAB exists
      run: ls -l app/build/outputs/bundle/release/

    - name: Rename AAB file
      run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/sul-game-wiki.aab

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sul-game-wiki
        path: app/build/outputs/bundle/release/sul-game-wiki.aab

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: sul-game-wiki
        path: app/build/outputs/bundle/release/

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Upload AAB to Synology NAS
      env:
        SYNOSSH_HOST: ${{ secrets.SYNOSSH_HOST }}
        SYNOSSH_USERNAME: ${{ secrets.SYNOSSH_USERNAME }}
        SYNOSSH_PASSWORD: ${{ secrets.SYNOSSH_PASSWORD }}
      run: |
        sshpass -p $SYNOSSH_PASSWORD scp -o StrictHostKeyChecking=no \
          app/build/outputs/bundle/release/sul-game-wiki.aab \
          $SYNOSSH_USERNAME@$SYNOSSH_HOST:/volume1/web/downloads/
