name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK to Synology NAS
      env:
        SYNOSSH_HOST: ${{ secrets.SYNOSSH_HOST }}
        SYNOSSH_USERNAME: ${{ secrets.SYNOSSH_USERNAME }}
        SYNOSSH_PASSWORD: ${{ secrets.SYNOSSH_PASSWORD }}
      run: |
        sudo apt-get update
        sudo apt-get install sshpass
        sshpass -p $SYNOSSH_PASSWORD scp -o StrictHostKeyChecking=no \
          app/build/outputs/apk/release/app-release.apk \
          $SYNOSSH_USERNAME@$SYNOSSH_HOST:/volume1/web/downloads/
